services:
  app:
    init: true
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - PDF_DEBUG=${PDF_DEBUG}

  db:
    image: postgres:16.4-alpine3.20
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}

volumes:
  db-data:
