services:
  app:
    init: true
    image: resume-thing-app
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - DB_URL=${DB_URL:-postgresql://postgres:postgres@db:5432/postgres}
      - PDF_DEBUG=${PDF_DEBUG}

  db-studio:
    image: resume-thing-app
    command: pnpm db:studio
    restart: always
    ports:
      - 4983:4983
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DB_URL=${DB_URL:-postgresql://postgres:postgres@db:5432/postgres}

  db:
    image: postgres:16.4-alpine3.20
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}

volumes:
  db-data:
